<!DOCTYPE html>
<html lang="en">
<head>
    <title>
    About Us
</title>
<link rel="stylesheet" href ="style.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<!--header section starts -->


<section class="header">
    <a href="home.php ">JIINUE YOUTH SACCO  </a>

    <nav class="navbar">
        <a href="home.html">Home</a>
        
        <a href="signup.php">Create Account </a>
</nav>

</section>
<!--header section ends-->

<div class="heading" style="background-image: url(beach.jpg)no-repeat">
    <h1>about us</h1>
</div>


<!-- about us details-->
<section class="about">
    <div class="content">
        <h3>Why choose us</h3>
        <p> Welcome to Jiinue Youth Sacco. We are a finance industry registered as a SACCO by the commissioner of co-operatives in Kenya.We offer 
            financial advice and services to young people in Kenya and empower them to save, invest and grow. </p>
         <h3> Vision </h3>
        <p> To provide quality information and services to youth to help them build themselves.</p> 
        <h3> Motto </h3>
        <p> Youth Empowerment for a better tomorrow </p>
        <h3>Mission</h3>
        <p> To economically transform lives of young people in Mathira and beyond through provision of innovative and affordable financial solutions.</p>
        
    </div>
</section>






















































<!--footer section starts-->

<section class="footer">
    <div class="box-container">
        <div class="box">
            <h3>quick links </h3>
        <a href="home.html"><i class="fa fa-angle-right"></i>home</a>
        <a href="aboutus.html"><i class="fa fa-angle-right"></i>about us</a>
       
        <a href="bookingpage.html"><i class="fa fa-angle-right"></i>book</a>
</div>
<div class="box">
            <h3>extra  links </h3>
        <a href="#"><i class="fa fa-angle-right"></i>ask questions</a>
        
       
</div>

<div class="box">
            <h3>contact info </h3>
           
        <a href="#"><i class="fa fa-phone"></i>0722333444</a>
        <a href="#"><i class="fa fa-phone"></i>0722333888</a>
        <a href="#"><i class="fa fa-envelope"></i>horizonairlines@gmail.com</a>
       
</div>

<div class="box">
            <h3>follow us </h3>
        <a href="#"><i class="fa fa-facebook"></i>facebook </a>
        <a href="#"><i class="fa fa-twitter"></i>Twitter</a>
        <a href="#"><i class="fa fa-instagram"></i>instagram</a>
        
</div>
    <div class="credit">All Rights Reserved.</div>


        
</div>

</section>





















<!--custom js file link-->
<script src="js/script.js"></script>
</body>
</html>